using System.Windows;

using Microsoft.Extensions.DependencyInjection;

using PsdUtilities.ApplicationModules.Models;

namespace ModularWpf.Application.Modules;

public sealed class ResourcesModule : IApplicationModule
{
    private readonly ResourceDictionary _resourceDictionary;

    public ApplicationModuleOrder Order { get; } = ApplicationModuleOrder.Default;

    public ResourcesModule(ResourceDictionary resourceDictionary)
    {
        _resourceDictionary = resourceDictionary;
    }

    public void Register(IServiceCollection services)
    {
        foreach (var uri in AutoGenerated.ResourceList.Uris)
            _resourceDictionary.MergedDictionaries.Add(new ResourceDictionary() { Source = uri });
    }
}